# Generated by Django 2.0.1 on 2018-01-17 16:19

from django.db import migrations
import edc_base.sites.managers


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aefollowup',
            managers=[
                ('on_site', edc_base.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='aeinitial',
            managers=[
                ('on_site', edc_base.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='aetmg',
            managers=[
                ('on_site', edc_base.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='recurrencesymptom',
            managers=[
                ('on_site', edc_base.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
