# Generated by Django 2.0 on 2017-12-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aefinal',
            name='tracking_identifier',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='aefollowup',
            name='tracking_identifier',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='aeinitial',
            name='tracking_identifier',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='aetmg',
            name='tracking_identifier',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalaefinal',
            name='tracking_identifier',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalaefollowup',
            name='tracking_identifier',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='tracking_identifier',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalaetmg',
            name='tracking_identifier',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
