# Generated by Django 2.0 on 2018-01-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeinitial',
            name='ambisome_relation',
            field=models.CharField(choices=[('not_related', 'Not related'), ('possibly_related', 'Possibly related'), ('probably_related', 'Probably related'), ('definitely_related', 'Definitely related'), ('unlikely_related', 'Unlikely related'), ('N/A', 'Not applicable')], max_length=25, verbose_name='Relationship to Ambisome:'),
        ),
        migrations.AlterField(
            model_name='aeinitial',
            name='amphotericin_b_relation',
            field=models.CharField(choices=[('not_related', 'Not related'), ('possibly_related', 'Possibly related'), ('probably_related', 'Probably related'), ('definitely_related', 'Definitely related'), ('unlikely_related', 'Unlikely related'), ('N/A', 'Not applicable')], max_length=25, verbose_name='Relationship to Amphotericin B:'),
        ),
        migrations.AlterField(
            model_name='aeinitial',
            name='fluconazole_relation',
            field=models.CharField(choices=[('not_related', 'Not related'), ('possibly_related', 'Possibly related'), ('probably_related', 'Probably related'), ('definitely_related', 'Definitely related'), ('unlikely_related', 'Unlikely related'), ('N/A', 'Not applicable')], max_length=25, verbose_name='Relationship to Fluconozole:'),
        ),
        migrations.AlterField(
            model_name='aeinitial',
            name='flucytosine_relation',
            field=models.CharField(choices=[('not_related', 'Not related'), ('possibly_related', 'Possibly related'), ('probably_related', 'Probably related'), ('definitely_related', 'Definitely related'), ('unlikely_related', 'Unlikely related'), ('N/A', 'Not applicable')], max_length=25, verbose_name='Relationship to Flucytosine:'),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='ambisome_relation',
            field=models.CharField(choices=[('not_related', 'Not related'), ('possibly_related', 'Possibly related'), ('probably_related', 'Probably related'), ('definitely_related', 'Definitely related'), ('unlikely_related', 'Unlikely related'), ('N/A', 'Not applicable')], max_length=25, verbose_name='Relationship to Ambisome:'),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='amphotericin_b_relation',
            field=models.CharField(choices=[('not_related', 'Not related'), ('possibly_related', 'Possibly related'), ('probably_related', 'Probably related'), ('definitely_related', 'Definitely related'), ('unlikely_related', 'Unlikely related'), ('N/A', 'Not applicable')], max_length=25, verbose_name='Relationship to Amphotericin B:'),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='fluconazole_relation',
            field=models.CharField(choices=[('not_related', 'Not related'), ('possibly_related', 'Possibly related'), ('probably_related', 'Probably related'), ('definitely_related', 'Definitely related'), ('unlikely_related', 'Unlikely related'), ('N/A', 'Not applicable')], max_length=25, verbose_name='Relationship to Fluconozole:'),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='flucytosine_relation',
            field=models.CharField(choices=[('not_related', 'Not related'), ('possibly_related', 'Possibly related'), ('probably_related', 'Probably related'), ('definitely_related', 'Definitely related'), ('unlikely_related', 'Unlikely related'), ('N/A', 'Not applicable')], max_length=25, verbose_name='Relationship to Flucytosine:'),
        ),
    ]
