# Generated by Django 2.0 on 2017-12-17 20:24

from django.db import migrations, models
import edc_base.model_fields.custom_fields
import edc_base.model_validators.date
import edc_base.utils
import edc_protocol.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0002_auto_20171216_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudyterminationconclusion',
            name='patient_terminated_date',
        ),
        migrations.RemoveField(
            model_name='studyterminationconclusion',
            name='patient_terminated_date',
        ),
        migrations.AddField(
            model_name='historicalstudyterminationconclusion',
            name='offstudy_datetime',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, validators=[edc_protocol.validators.datetime_not_before_study_start, edc_base.model_validators.date.datetime_not_future], verbose_name='Off-study date and time'),
        ),
        migrations.AddField(
            model_name='historicalstudyterminationconclusion',
            name='offstudy_reason',
            field=models.CharField(choices=[('lost', 'Lost to follow-up'), ('completed protocol', 'Completed protocol'), ('consent_withdrawal', 'Completed protocol'), ('dead', 'Deceased')], default='-', max_length=125, verbose_name='Please code the primary reason participant taken off-study'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalstudyterminationconclusion',
            name='offstudy_reason_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If Other, specify ...'),
        ),
        migrations.AddField(
            model_name='studyterminationconclusion',
            name='offstudy_datetime',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, validators=[edc_protocol.validators.datetime_not_before_study_start, edc_base.model_validators.date.datetime_not_future], verbose_name='Off-study date and time'),
        ),
        migrations.AddField(
            model_name='studyterminationconclusion',
            name='offstudy_reason',
            field=models.CharField(choices=[('lost', 'Lost to follow-up'), ('completed protocol', 'Completed protocol'), ('consent_withdrawal', 'Completed protocol'), ('dead', 'Deceased')], default='-', max_length=125, verbose_name='Please code the primary reason participant taken off-study'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyterminationconclusion',
            name='offstudy_reason_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If Other, specify ...'),
        ),
        migrations.AlterField(
            model_name='aetmg',
            name='ae_classification',
            field=models.ManyToManyField(blank=True, to='ambition_ae.AeClassification', verbose_name='Classification of AE:'),
        ),
        migrations.AlterField(
            model_name='historicalstudyterminationconclusion',
            name='readmission_after_initial_discharge',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=7, verbose_name='Was the patient re-admitted following initial discharge?'),
        ),
        migrations.AlterField(
            model_name='historicalstudyterminationconclusion',
            name='subject_identifier',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Subject Identifier'),
        ),
        migrations.AlterField(
            model_name='studyterminationconclusion',
            name='readmission_after_initial_discharge',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=7, verbose_name='Was the patient re-admitted following initial discharge?'),
        ),
        migrations.AlterField(
            model_name='studyterminationconclusion',
            name='subject_identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name='Subject Identifier'),
        ),
    ]
