# Generated by Django 2.0 on 2017-12-04 17:40

from django.db import migrations, models
import edc_base.model_validators.date
import edc_base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0002_auto_20171204_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeinitial',
            name='ae_awareness_date',
            field=models.DateField(default=edc_base.utils.get_utcnow, validators=[edc_base.model_validators.date.date_not_future], verbose_name='AE Awareness date'),
        ),
        migrations.AlterField(
            model_name='aeinitial',
            name='ae_start_date',
            field=models.DateField(default=edc_base.utils.get_utcnow, validators=[edc_base.model_validators.date.date_not_future], verbose_name='Actual Start Date of AE'),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='ae_awareness_date',
            field=models.DateField(default=edc_base.utils.get_utcnow, validators=[edc_base.model_validators.date.date_not_future], verbose_name='AE Awareness date'),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='ae_start_date',
            field=models.DateField(default=edc_base.utils.get_utcnow, validators=[edc_base.model_validators.date.date_not_future], verbose_name='Actual Start Date of AE'),
        ),
    ]
