# Generated by Django 2.0.1 on 2018-01-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0002_auto_20180104_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aefollowup',
            name='ae_grade',
            field=models.CharField(choices=[('4', 'Grade 4 - Life-threatening'), ('5', 'Grade 5 - Death'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='If severity increased, indicate grade'),
        ),
        migrations.AlterField(
            model_name='aefollowup',
            name='outcome',
            field=models.CharField(choices=[('continuing/update', 'Continuing/Update'), ('increase_from_g3', 'Severity increased from Grade III'), ('recovered', 'Recovered/Resolved'), ('recovering', 'Recovering/Resolving at end of study'), ('not_recovered', 'Not Recovered/Resolved at end of study'), ('LTFU', 'Unknown/Lost to follow-up'), ('recovered_with_sequelae', 'Recovered with sequelae'), ('dead', 'Death')], max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalaefollowup',
            name='ae_grade',
            field=models.CharField(choices=[('4', 'Grade 4 - Life-threatening'), ('5', 'Grade 5 - Death'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='If severity increased, indicate grade'),
        ),
        migrations.AlterField(
            model_name='historicalaefollowup',
            name='outcome',
            field=models.CharField(choices=[('continuing/update', 'Continuing/Update'), ('increase_from_g3', 'Severity increased from Grade III'), ('recovered', 'Recovered/Resolved'), ('recovering', 'Recovering/Resolving at end of study'), ('not_recovered', 'Not Recovered/Resolved at end of study'), ('LTFU', 'Unknown/Lost to follow-up'), ('recovered_with_sequelae', 'Recovered with sequelae'), ('dead', 'Death')], max_length=25),
        ),
    ]
