# Generated by Django 2.0.7 on 2018-07-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0003_auto_20180707_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aefollowup',
            name='outcome',
            field=models.CharField(choices=[('continuing/update', 'Continuing/Update'), ('increase_from_g3', 'Severity increased from Grade III'), ('recovered', 'Recovered/Resolved'), ('recovering', 'Recovering/Resolving at end of study'), ('not_recovered', 'Not Recovered/Resolved at end of study'), ('LTFU', 'Unknown/Lost to follow-up'), ('recovered_with_sequelae', 'Recovered with sequelae')], max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalaefollowup',
            name='outcome',
            field=models.CharField(choices=[('continuing/update', 'Continuing/Update'), ('increase_from_g3', 'Severity increased from Grade III'), ('recovered', 'Recovered/Resolved'), ('recovering', 'Recovering/Resolving at end of study'), ('not_recovered', 'Not Recovered/Resolved at end of study'), ('LTFU', 'Unknown/Lost to follow-up'), ('recovered_with_sequelae', 'Recovered with sequelae')], max_length=25),
        ),
    ]
