# Generated by Django 2.0.1 on 2018-01-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0003_auto_20180105_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetmg',
            name='ae_classification',
            field=models.ManyToManyField(to='ambition_ae.AeClassification', verbose_name='Classification of AE:'),
        ),
        migrations.AlterField(
            model_name='recurrencesymptom',
            name='antibiotic_treatment',
            field=models.ManyToManyField(to='ambition_ae.AntibioticTreatment', verbose_name='Antibiotics treatment'),
        ),
        migrations.AlterField(
            model_name='recurrencesymptom',
            name='meningitis_symptom',
            field=models.ManyToManyField(to='ambition_ae.MeningitisSymptom', verbose_name='What are your current symptoms?'),
        ),
        migrations.AlterField(
            model_name='recurrencesymptom',
            name='neurological',
            field=models.ManyToManyField(to='ambition_ae.Neurological', verbose_name='neurologic:'),
        ),
    ]
