# Generated by Django 2.0 on 2017-12-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0003_auto_20171217_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deathreporttmgone',
            name='death_report',
        ),
        migrations.RemoveField(
            model_name='deathreporttmgtwo',
            name='death_report',
        ),
        migrations.RemoveField(
            model_name='historicaldeathreport',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldeathreporttmgone',
            name='death_report',
        ),
        migrations.RemoveField(
            model_name='historicaldeathreporttmgone',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldeathreporttmgtwo',
            name='death_report',
        ),
        migrations.RemoveField(
            model_name='historicaldeathreporttmgtwo',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprotocoldeviationviolation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstudyterminationconclusion',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='ProtocolDeviationViolation',
        ),
        migrations.DeleteModel(
            name='StudyTerminationConclusion',
        ),
        migrations.AlterField(
            model_name='aetmg',
            name='ae_classification',
            field=models.ManyToManyField(blank=True, to='ambition_ae.AeClassification', verbose_name='Classification of AE:'),
        ),
        migrations.DeleteModel(
            name='DeathReport',
        ),
        migrations.DeleteModel(
            name='DeathReportTmgOne',
        ),
        migrations.DeleteModel(
            name='DeathReportTmgTwo',
        ),
        migrations.DeleteModel(
            name='HistoricalDeathReport',
        ),
        migrations.DeleteModel(
            name='HistoricalDeathReportTmgOne',
        ),
        migrations.DeleteModel(
            name='HistoricalDeathReportTmgTwo',
        ),
        migrations.DeleteModel(
            name='HistoricalProtocolDeviationViolation',
        ),
        migrations.DeleteModel(
            name='HistoricalStudyTerminationConclusion',
        ),
    ]
