# Generated by Django 2.0 on 2017-12-06 00:58

from django.db import migrations, models
import edc_base.model_validators.date


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0003_auto_20171204_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aefinal',
            name='ae_initial',
        ),
        migrations.RemoveField(
            model_name='historicalaefinal',
            name='ae_initial',
        ),
        migrations.RemoveField(
            model_name='historicalaefinal',
            name='history_user',
        ),
        migrations.AlterField(
            model_name='aefollowup',
            name='outcome_date',
            field=models.DateField(validators=[edc_base.model_validators.date.date_not_future]),
        ),
        migrations.AlterField(
            model_name='aeinitial',
            name='tmg_report_datetime',
            field=models.DateTimeField(blank=True, help_text='AEs ≥ Grade 4 or SAE must be reported to the Trial Management Group (TMG) within 48hrs (Email to: user@example.com', null=True, verbose_name='Date and time AE reported to TMG'),
        ),
        migrations.AlterField(
            model_name='historicalaefollowup',
            name='outcome_date',
            field=models.DateField(validators=[edc_base.model_validators.date.date_not_future]),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='tmg_report_datetime',
            field=models.DateTimeField(blank=True, help_text='AEs ≥ Grade 4 or SAE must be reported to the Trial Management Group (TMG) within 48hrs (Email to: user@example.com', null=True, verbose_name='Date and time AE reported to TMG'),
        ),
        migrations.DeleteModel(
            name='AeFinal',
        ),
        migrations.DeleteModel(
            name='HistoricalAeFinal',
        ),
    ]
