# Generated by Django 2.0 on 2017-12-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0004_auto_20171206_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeinitial',
            name='tmg_report_datetime',
            field=models.DateTimeField(blank=True, help_text='AEs ≥ Grade 4 or SAE must be reported to the Trial Management Group (TMG) within 48hrs (Email to: ambitionreporting@lshtm.ac.uk', null=True, verbose_name='Date and time AE reported to TMG'),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='tmg_report_datetime',
            field=models.DateTimeField(blank=True, help_text='AEs ≥ Grade 4 or SAE must be reported to the Trial Management Group (TMG) within 48hrs (Email to: ambitionreporting@lshtm.ac.uk', null=True, verbose_name='Date and time AE reported to TMG'),
        ),
    ]
