# Generated by Django 2.0.1 on 2018-01-05 11:41

from django.db import migrations, models
import edc_base.model_validators.date


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0004_auto_20180105_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aetmg',
            name='investigator_returned',
        ),
        migrations.RemoveField(
            model_name='historicalaetmg',
            name='investigator_returned',
        ),
        migrations.AddField(
            model_name='aetmg',
            name='report_closed_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.date_not_future], verbose_name='Date and time report closed.'),
        ),
        migrations.AddField(
            model_name='aetmg',
            name='report_status',
            field=models.CharField(choices=[('open', 'Open. Some information is still pending.'), ('closed', 'Closed. This report is complete')], default='Open', max_length=25, verbose_name='What is the status of this report?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalaetmg',
            name='report_closed_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.date_not_future], verbose_name='Date and time report closed.'),
        ),
        migrations.AddField(
            model_name='historicalaetmg',
            name='report_status',
            field=models.CharField(choices=[('open', 'Open. Some information is still pending.'), ('closed', 'Closed. This report is complete')], default='Open', max_length=25, verbose_name='What is the status of this report?'),
            preserve_default=False,
        ),
    ]
