# Generated by Django 2.0 on 2017-12-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0005_auto_20171219_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetmg',
            name='ae_classification',
            field=models.ManyToManyField(blank=True, to='ambition_ae.AeClassification', verbose_name='Classification of AE:'),
        ),
    ]
