# Generated by Django 2.0 on 2017-12-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0005_auto_20171206_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aefollowup',
            name='outcome',
            field=models.CharField(choices=[('continuing/update', 'Continuing/Update'), ('recovered', 'Recovered/Resolved'), ('recovering', 'Recovering/Resolving at end of study'), ('not_recovered', 'Not Recovered/Resolved at end of study'), ('unknown', 'Unknown/Lost to follow-up'), ('recovered_with_sequelae', 'Recovered with sequelae'), ('Death', 'Death')], max_length=25),
        ),
        migrations.AlterField(
            model_name='aeinitial',
            name='ae_grade',
            field=models.CharField(choices=[('3', 'Grade III - Severe'), ('4', 'Grade 4 - Life-threatening'), ('5', 'Grade 5 - Death')], max_length=25, verbose_name='Severity of AE'),
        ),
        migrations.AlterField(
            model_name='aeinitial',
            name='regimen',
            field=models.CharField(help_text='Control: (Amphotericin B 1 mg/kg for 7 days with flucytosine 100mg/kg/day for 7 days followed by fluconazole 1200mg/day for 7 days)Single: Ambisome 10mg/kg on day 1 with flucytosine 100mg/kg/day and fluconazole 1200mg/day for 14 days', max_length=50, verbose_name='Patient’s treatment regimen'),
        ),
        migrations.AlterField(
            model_name='aeinitial',
            name='tmg_report_datetime',
            field=models.DateTimeField(blank=True, help_text='AEs ≥ Grade 4 or SAE must be reported to the Trial Management Group (TMG) within 24 hours (Email to: ambitionreporting@lshtm.ac.uk', null=True, verbose_name='Date and time AE reported to TMG'),
        ),
        migrations.AlterField(
            model_name='historicalaefollowup',
            name='outcome',
            field=models.CharField(choices=[('continuing/update', 'Continuing/Update'), ('recovered', 'Recovered/Resolved'), ('recovering', 'Recovering/Resolving at end of study'), ('not_recovered', 'Not Recovered/Resolved at end of study'), ('unknown', 'Unknown/Lost to follow-up'), ('recovered_with_sequelae', 'Recovered with sequelae'), ('Death', 'Death')], max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='ae_grade',
            field=models.CharField(choices=[('3', 'Grade III - Severe'), ('4', 'Grade 4 - Life-threatening'), ('5', 'Grade 5 - Death')], max_length=25, verbose_name='Severity of AE'),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='regimen',
            field=models.CharField(help_text='Control: (Amphotericin B 1 mg/kg for 7 days with flucytosine 100mg/kg/day for 7 days followed by fluconazole 1200mg/day for 7 days)Single: Ambisome 10mg/kg on day 1 with flucytosine 100mg/kg/day and fluconazole 1200mg/day for 14 days', max_length=50, verbose_name='Patient’s treatment regimen'),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='tmg_report_datetime',
            field=models.DateTimeField(blank=True, help_text='AEs ≥ Grade 4 or SAE must be reported to the Trial Management Group (TMG) within 24 hours (Email to: ambitionreporting@lshtm.ac.uk', null=True, verbose_name='Date and time AE reported to TMG'),
        ),
    ]
