# Generated by Django 2.0.1 on 2018-01-05 11:59

from django.db import migrations, models
import edc_base.model_validators.date
import edc_base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0005_auto_20180105_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetmg',
            name='ae_received_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Date and time AE form received:'),
        ),
        migrations.AlterField(
            model_name='aetmg',
            name='clinical_review_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Date and time of clinical review: '),
        ),
        migrations.AlterField(
            model_name='aetmg',
            name='officials_notified',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Date and time regulatory authorities notified (SUSARs)'),
        ),
        migrations.AlterField(
            model_name='aetmg',
            name='report_closed_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Date and time report closed.'),
        ),
        migrations.AlterField(
            model_name='aetmg',
            name='report_datetime',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Report date and time'),
        ),
        migrations.AlterField(
            model_name='historicalaetmg',
            name='ae_received_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Date and time AE form received:'),
        ),
        migrations.AlterField(
            model_name='historicalaetmg',
            name='clinical_review_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Date and time of clinical review: '),
        ),
        migrations.AlterField(
            model_name='historicalaetmg',
            name='officials_notified',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Date and time regulatory authorities notified (SUSARs)'),
        ),
        migrations.AlterField(
            model_name='historicalaetmg',
            name='report_closed_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Date and time report closed.'),
        ),
        migrations.AlterField(
            model_name='historicalaetmg',
            name='report_datetime',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Report date and time'),
        ),
    ]
