# Generated by Django 2.0.1 on 2018-01-06 22:37

from django.db import migrations, models
import edc_base.model_fields.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0006_auto_20180105_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeinitial',
            name='ae_cause_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=250, null=True, verbose_name='If "Yes", specify'),
        ),
        migrations.AlterField(
            model_name='aeinitial',
            name='ae_cm_recurrence',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='unknown', help_text='If "Yes", fill in the "Recurrence of Symptoms" form', max_length=10, verbose_name='Was the AE a recurrence of CM symptoms?'),
        ),
        migrations.AlterField(
            model_name='aeinitial',
            name='sae_reason',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('dead', 'Death'), ('life_threatening', 'Life-threatening'), ('significant_disability', 'Significant disability'), ('in-patient_hospitalization', 'In-patient hospitalization or prolongation (beyond 1 week from study inclusion)'), ('medically_important_event', 'Medically important event (e.g. Severe thrombophlebitis, Bacteraemia, recurrence of symptoms not requiring admission, Hospital acquired pneumonia)')], default='N/A', help_text='If subject deceased, submit a Death Report', max_length=50, verbose_name='If "Yes", reason for SAE:'),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='ae_cause_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=250, null=True, verbose_name='If "Yes", specify'),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='ae_cm_recurrence',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='unknown', help_text='If "Yes", fill in the "Recurrence of Symptoms" form', max_length=10, verbose_name='Was the AE a recurrence of CM symptoms?'),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='sae_reason',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('dead', 'Death'), ('life_threatening', 'Life-threatening'), ('significant_disability', 'Significant disability'), ('in-patient_hospitalization', 'In-patient hospitalization or prolongation (beyond 1 week from study inclusion)'), ('medically_important_event', 'Medically important event (e.g. Severe thrombophlebitis, Bacteraemia, recurrence of symptoms not requiring admission, Hospital acquired pneumonia)')], default='N/A', help_text='If subject deceased, submit a Death Report', max_length=50, verbose_name='If "Yes", reason for SAE:'),
        ),
    ]
