# Generated by Django 2.0 on 2017-12-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0006_auto_20171212_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aefollowup',
            name='outcome',
            field=models.CharField(choices=[('continuing/update', 'Continuing/Update'), ('recovered', 'Recovered/Resolved'), ('recovering', 'Recovering/Resolving at end of study'), ('not_recovered', 'Not Recovered/Resolved at end of study'), ('unknown', 'Unknown/Lost to follow-up'), ('recovered_with_sequelae', 'Recovered with sequelae'), ('death', 'Death')], max_length=25),
        ),
        migrations.AlterField(
            model_name='aeinitial',
            name='sae_reason',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('death', 'Death (Please complete Death form and Study termination form)'), ('life_threatening', 'Life-threatening'), ('significant_disability', 'Significant disability'), ('in-patient_hospitalization', 'In-patient hospitalization or prolongation (beyond 1 week from study inclusion)'), ('medically_important_event', 'Medically important event (e.g. Severe thrombophlebitis, Bacteraemia, recurrence of symptoms not requiring admission, Hospital acquired pneumonia)')], default='N/A', max_length=50, verbose_name='If Yes, Reason for SAE:'),
        ),
        migrations.AlterField(
            model_name='aeinitial',
            name='tmg_report_datetime',
            field=models.DateTimeField(blank=True, help_text='AEs ≥ Grade 4 or SAE must be reported to the Trial Management Group (TMG) within 24 hours (Email to: user@example.com', null=True, verbose_name='Date and time AE reported to TMG'),
        ),
        migrations.AlterField(
            model_name='historicalaefollowup',
            name='outcome',
            field=models.CharField(choices=[('continuing/update', 'Continuing/Update'), ('recovered', 'Recovered/Resolved'), ('recovering', 'Recovering/Resolving at end of study'), ('not_recovered', 'Not Recovered/Resolved at end of study'), ('unknown', 'Unknown/Lost to follow-up'), ('recovered_with_sequelae', 'Recovered with sequelae'), ('death', 'Death')], max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='sae_reason',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('death', 'Death (Please complete Death form and Study termination form)'), ('life_threatening', 'Life-threatening'), ('significant_disability', 'Significant disability'), ('in-patient_hospitalization', 'In-patient hospitalization or prolongation (beyond 1 week from study inclusion)'), ('medically_important_event', 'Medically important event (e.g. Severe thrombophlebitis, Bacteraemia, recurrence of symptoms not requiring admission, Hospital acquired pneumonia)')], default='N/A', max_length=50, verbose_name='If Yes, Reason for SAE:'),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='tmg_report_datetime',
            field=models.DateTimeField(blank=True, help_text='AEs ≥ Grade 4 or SAE must be reported to the Trial Management Group (TMG) within 24 hours (Email to: user@example.com', null=True, verbose_name='Date and time AE reported to TMG'),
        ),
    ]
