# Generated by Django 2.0.1 on 2018-01-11 19:33

from django.db import migrations, models
import edc_base.model_fields.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0007_auto_20180107_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aeinitial',
            name='ae_name',
        ),
        migrations.RemoveField(
            model_name='historicalaeinitial',
            name='ae_name',
        ),
        migrations.AddField(
            model_name='aeinitial',
            name='ae_classification',
            field=models.CharField(choices=[('anaemia', 'Anaemia'), ('bacteraemia/sepsis', 'Bacteraemia/Sepsis'), ('CM_IRIS', 'CM IRIS'), ('diarrhoea', 'Diarrhoea'), ('hypokalaemia', 'Hypokalaemia'), ('neutropaenia', 'Neutropaenia'), ('pneumonia', 'Pneumonia'), ('respiratory_distress', 'Respiratory distress'), ('TB', 'TB'), ('thrombocytopenia', 'Thrombocytopenia'), ('thrombophlebitis', 'Renal impairment'), ('OTHER', 'Other')], default='TB', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aeinitial',
            name='ae_classification_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=250, null=True, verbose_name='If Other, specify ...'),
        ),
        migrations.AddField(
            model_name='historicalaeinitial',
            name='ae_classification',
            field=models.CharField(choices=[('anaemia', 'Anaemia'), ('bacteraemia/sepsis', 'Bacteraemia/Sepsis'), ('CM_IRIS', 'CM IRIS'), ('diarrhoea', 'Diarrhoea'), ('hypokalaemia', 'Hypokalaemia'), ('neutropaenia', 'Neutropaenia'), ('pneumonia', 'Pneumonia'), ('respiratory_distress', 'Respiratory distress'), ('TB', 'TB'), ('thrombocytopenia', 'Thrombocytopenia'), ('thrombophlebitis', 'Renal impairment'), ('OTHER', 'Other')], default='TB', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalaeinitial',
            name='ae_classification_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=250, null=True, verbose_name='If Other, specify ...'),
        ),
        migrations.AddField(
            model_name='historicalaetmg',
            name='ae_classification',
            field=models.CharField(choices=[('anaemia', 'Anaemia'), ('bacteraemia/sepsis', 'Bacteraemia/Sepsis'), ('CM_IRIS', 'CM IRIS'), ('diarrhoea', 'Diarrhoea'), ('hypokalaemia', 'Hypokalaemia'), ('neutropaenia', 'Neutropaenia'), ('pneumonia', 'Pneumonia'), ('respiratory_distress', 'Respiratory distress'), ('TB', 'TB'), ('thrombocytopenia', 'Thrombocytopenia'), ('thrombophlebitis', 'Renal impairment'), ('OTHER', 'Other')], default='TB', max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='aetmg',
            name='ae_classification',
        ),
        migrations.AddField(
            model_name='aetmg',
            name='ae_classification',
            field=models.CharField(choices=[('anaemia', 'Anaemia'), ('bacteraemia/sepsis', 'Bacteraemia/Sepsis'), ('CM_IRIS', 'CM IRIS'), ('diarrhoea', 'Diarrhoea'), ('hypokalaemia', 'Hypokalaemia'), ('neutropaenia', 'Neutropaenia'), ('pneumonia', 'Pneumonia'), ('respiratory_distress', 'Respiratory distress'), ('TB', 'TB'), ('thrombocytopenia', 'Thrombocytopenia'), ('thrombophlebitis', 'Renal impairment'), ('OTHER', 'Other')], default='TB', max_length=50),
            preserve_default=False,
        ),
    ]
