# Generated by Django 2.0.1 on 2018-01-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0008_auto_20180111_2133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AeClassification',
        ),
    ]
