# Generated by Django 2.0.1 on 2018-01-11 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0009_delete_aeclassification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetmg',
            name='ae_initial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ambition_ae.AeInitial'),
        ),
    ]
