# Generated by Django 2.1 on 2018-10-01 19:12

from django.db import migrations
from edc_action_item.utils import fix_null_action_item_fk


def fix(apps, schema_editor):
    fix_null_action_item_fk(
        apps,
        app_label='ambition_ae',
        models=['aeinitial',
                'aefollowup',
                'recurrencesymptom',
                'aetmg']
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0012_auto_20181001_2112'),
        ('edc_action_item', '0014_auto_20181003_0614'),
    ]

    operations = [migrations.RunPython(fix)]
