# Generated by Django 2.1 on 2018-10-06 02:28

import edc_action_item.managers

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0013_auto_20181002_0411'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aefollowup',
            managers=[
                ('on_site', edc_action_item.managers.ActionIdentifierSiteManager()),
                ('objects', edc_action_item.managers.ActionIdentifierManager()),
            ],
        ),
        migrations.AlterField(
            model_name='aefollowup',
            name='action_identifier',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='aeinitial',
            name='action_identifier',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='aetmg',
            name='action_identifier',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalaefollowup',
            name='action_identifier',
            field=models.CharField(db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='action_identifier',
            field=models.CharField(db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='historicalaetmg',
            name='action_identifier',
            field=models.CharField(db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='historicalrecurrencesymptom',
            name='action_identifier',
            field=models.CharField(db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='recurrencesymptom',
            name='action_identifier',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
