# Generated by Django 2.1 on 2018-10-06 02:15

from django.db import migrations
from edc_action_item.utils import fix_null_historical_action_identifier


def fix(apps, schema_editor):
    fix_null_historical_action_identifier(
        app_label='ambition_ae',
        models=[
            'aeinitial',
            'aefollowup',
            'recurrencesymptom',
            'aetmg']
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0014_auto_20181004_0409'),
    ]

    operations = [migrations.RunPython(fix)]
